### Numpy

In [1]:
from scipy.stats import variation
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## identiity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
### vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### elementwise addition
print("Addition:", arr1 + arr2)

### substraction
print("Subtraction:", arr1 - arr2)

### multiplications
print("Multiplication:", arr1 * arr2)

### Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [18]:
### universal function
arr = np.array([1,2,3,4,5])
## squareroor
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [19]:
### slicings and indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10], [10,20,30,40,50]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [10 20 30 40 50]]


In [20]:
arr[0]

array([1, 2, 3, 4, 5])

In [21]:
arr[1:,2:]

array([[ 8,  9, 10],
       [30, 40, 50]])

In [24]:
print(arr[0:2,2:])

[[ 3  4  5]
 [ 8  9 10]]


In [25]:
print(arr[1:, 1:3])

[[ 7  8]
 [20 30]]


In [26]:
### modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 10  20  30  40  50]]


In [27]:
arr[1:] = 150
print(arr)

[[100   2   3   4   5]
 [150 150 150 150 150]
 [150 150 150 150 150]]


In [29]:
### statistical concepts - normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)
norm_data = (data - mean) / std_dev
variation = np.var(data)
print("normalized data:", norm_data)
print(variation)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
2.0


In [33]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data[data > 5])
print(data[(data > 5) & (data < 9)])

[ 6  7  8  9 10]
[6 7 8]
