In [1]:
### importing numpy
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
## add dimentions while declaring
exp2 = np.array([1,2,3,4,5], ndmin=3)
print(exp2)

[[[1 2 3 4 5]]]


In [4]:
## read the dimentions
exp2.ndim

3

In [5]:
## indexing one dimentions
exp = np.array([1,2,3,4,5])
print(exp[0])
print(exp[2])
print(exp[1:3])
print(exp[-1])

1
3
[2 3]
5


In [6]:
## indexing 2-D array
twodim = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(twodim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
print(twodim[0,2])

3


In [8]:
print(twodim[0,2:5])

[3 4 5]


In [9]:
print(twodim[-1,2:5])

[ 8  9 10]


In [10]:
## indexing 3-D array
threedim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [11]:
print(threedim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(threedim.shape)

(2, 2, 3)


In [13]:
print(threedim[0,1,2])

6


In [14]:
print(threedim[1,1,0])

10


In [15]:
print(threedim[-1,1,2])

12


In [16]:
## slicing an array
ar1 = np.array([1,2,3,4,5])
print(ar1[1:3])

[2 3]


In [17]:
print(ar1[:2])

[1 2]


In [18]:
## negative slicing
print(ar1[-2:])

[4 5]


In [19]:
print(ar1[-3:-1])

[3 4]


In [20]:
## use stepper
print(ar1[1:3:2])

[2]


In [21]:
## prints everyother element from an array
print(ar1[::2])

[1 3 5]


In [22]:
print(twodim[1,1:4])

[7 8 9]


In [23]:
print(twodim[0:2, 2])

[3 8]


In [24]:
print(twodim[0:2, 1:3])

[[2 3]
 [7 8]]


In [25]:
### Datatypes in Numpy
#### i - integer
#### b - boolean
#### u - unsigned integer
#### f - float
#### c - complex
#### m - timedelta
#### M - datetime
#### O - object
#### S - String
#### U - unicode string
#### V - fixed chunk of memory for other type (void)

In [26]:
## printing data type of an array
print(ar1.dtype)

int32


In [27]:
array2 = np.array(["apple", "banana", "cherry"])
print(array2.dtype)

<U6


In [28]:
array3 = np.array([1,2,3], dtype='S')
print(array3.dtype)

|S1


In [29]:
array3 = np.array([1,2,3], dtype='i4')
print(array3.dtype)

int32


In [30]:
print(array3)

[1 2 3]


In [31]:
## copy
array4 = array3.copy()
array4[0] = 99
print(array4)
print(array3)

[99  2  3]
[1 2 3]


In [32]:
## view
array5 = array3.view()
array5[0] = 99
print(array5)
print(array3)

[99  2  3]
[99  2  3]


In [33]:
## array shapes
ar4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(ar4.shape)

(2, 5)


In [34]:
ar5 = np.array([1,2,3,4,5], ndmin=3) ## create an array with 3 dimension using ndmin using a vector with values 1,2,3,4,5 and verify that last dimension has value 5
print(ar5.shape)
print(ar5)

(1, 1, 5)
[[[1 2 3 4 5]]]


In [35]:
ar6 = np.array([-1,0,1])
newar = ar6.astype(bool)
print(newar)

[ True False  True]


In [36]:
## Reshaping into 3 X 2 Matrix
ar7 = np.array([1,2,3,4,5,6]).reshape(3,2)

In [37]:
print(ar7)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
## 2X3 Matrix
ar7 = np.array([1,2,3,4,5,6]).reshape(2,3)
print(ar7)

[[1 2 3]
 [4 5 6]]


In [39]:
## iterations 1-D
ar8 = np.array([1,2,3,4,5,6])
for i in ar8:
    print(i)

1
2
3
4
5
6


In [40]:
## 2D iteration
ar9 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in ar9:
    for j in i:
        print(i, j)

[1 2 3 4 5] 1
[1 2 3 4 5] 2
[1 2 3 4 5] 3
[1 2 3 4 5] 4
[1 2 3 4 5] 5
[ 6  7  8  9 10] 6
[ 6  7  8  9 10] 7
[ 6  7  8  9 10] 8
[ 6  7  8  9 10] 9
[ 6  7  8  9 10] 10


In [41]:
## 3D iterations
ar10 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

In [42]:
for i in ar10:
    for j in i:
        for k in j:
            print(i, j, k)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 3
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 4
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 6
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 7
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 8
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 9
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 10
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 11
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 12
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 13
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 14
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 15
[[11 12 13 14 15]
 [16 17 18 19 20]] [16 17 18 19 20] 16
[[11 12 13 14 15]
 [16 17 18 19 20]] [16 17 18 19 20] 17
[[11 12 13 14 15]
 [16 17 18 19 20]] [16 17 18 19 20] 18
[[11 12 

In [43]:
for i in np.nditer(ar10):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [44]:
for i in np.nditer(ar10, flags=['buffered'], op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'13'
b'14'
b'15'
b'16'
b'17'
b'18'
b'19'
b'20'


In [45]:
for i in np.nditer(ar10[:,::2]):
    print(i)

1
2
3
4
5
11
12
13
14
15


In [46]:
for idx, i in np.ndenumerate(ar10):
    print(idx, i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20


In [47]:
ar11 = np.array([[1,2,3], [4,5,6]]).reshape(6)
print(ar11)

[1 2 3 4 5 6]


In [48]:
ar11 = np.array([[1,2,3], [4,5,6]]).reshape(-1)
print(ar11)

[1 2 3 4 5 6]


In [49]:
## joins
ar12 = np.array([1,2])
ar13 = np.array([3,4])
print(np.concatenate((ar12, ar13)))

[1 2 3 4]


In [50]:
ar14 = np.array([[1,2,3], [4,5,6]])
ar15 = np.array([[7,8,9], [10,11,12]])
print(np.concatenate((ar14, ar15), axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [51]:
print(np.hstack((ar14, ar15)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [52]:
print(np.vstack((ar14, ar15)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [53]:
print(np.dstack((ar14, ar15)))

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [56]:
## splitting of array
ar16 = np.array_split([1,2,3,4], 2)
print(ar16)

[array([1, 2]), array([3, 4])]


In [58]:
ar17 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(np.array_split(ar17, 3))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(np.array_split(arr, 3))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [63]:
### Searching Arrays
arr = np.array([1, 2, 3, 4, 5, 4, 4])
'''
You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method.
'''
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [ ]:
arr = np.array([6, 7, 8, 9])
'''
There is a method called searchsorted() which performs a binary search in the array, 
and returns the index where the specified value would be inserted to maintain the search order.
'''
x = np.searchsorted(arr, 7)
print(x)

1


In [ ]:
arr = np.array([6, 7, 8, 9])
'''
By default the left most index is returned, but we can give side='right' to return the right most index instead.
'''
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [70]:
arr = np.array([1, 3, 5, 7])
### To search for more than one value, use an array with the specified values.
x = np.searchsorted(arr, [2, 4, 6])
### The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.
print(x)

[1 2 3]


In [71]:
### Sorting Arrays
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [72]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [73]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [74]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [75]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [76]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [77]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [79]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [80]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
