In [1]:
### importing numpy
import numpy as np

In [3]:
array = np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
## add dimentions while declaring
exp2 = np.array([1,2,3,4,5], ndmin=3)
print(exp2)

[[[1 2 3 4 5]]]


In [5]:
## read the dimentions
exp2.ndim

3

In [7]:
## indexing one dimentions
exp = np.array([1,2,3,4,5])
print(exp[0])
print(exp[2])
print(exp[1:3])
print(exp[-1])

1
3
[2 3]
5


In [8]:
## indexing 2-D array
twodim = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(twodim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
print(twodim[0,2])

3


In [12]:
print(twodim[0,2:5])

[3 4 5]


In [11]:
print(twodim[-1,2:5])

[ 8  9 10]


In [18]:
## indexing 3-D array
threedim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [19]:
print(threedim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
print(threedim.shape)

(2, 2, 3)


In [21]:
print(threedim[0,1,2])

6


In [22]:
print(threedim[1,1,0])

10


In [24]:
print(threedim[-1,1,2])

12


In [25]:
## slicing an array
ar1 = np.array([1,2,3,4,5])
print(ar1[1:3])

[2 3]


In [26]:
print(ar1[:2])

[1 2]


In [27]:
## negative slicing
print(ar1[-2:])

[4 5]


In [28]:
print(ar1[-3:-1])

[3 4]


In [29]:
## use stepper
print(ar1[1:3:2])

[2]


In [30]:
## prints everyother element from an array
print(ar1[::2])

[1 3 5]


In [31]:
print(twodim[1,1:4])

[7 8 9]


In [32]:
print(twodim[0:2, 2])

[3 8]


In [34]:
print(twodim[0:2, 1:3])

[[2 3]
 [7 8]]


In [35]:
### Datatypes in Numpy
#### i - integer
#### b - boolean
#### u - unsigned integer
#### f - float
#### c - complex
#### m - timedelta
#### M - datetime
#### O - object
#### S - String
#### U - unicode string
#### V - fixed chunk of memory for other type (void)

In [37]:
## printing data type of an array
print(ar1.dtype)

int64


In [38]:
array2 = np.array(["apple", "banana", "cherry"])
print(array2.dtype)

<U6


In [39]:
array3 = np.array([1,2,3], dtype='S')
print(array3.dtype)

|S1


In [40]:
array3 = np.array([1,2,3], dtype='i4')
print(array3.dtype)

int32


In [41]:
print(array3)

[1 2 3]


In [42]:
## copy
array4 = array3.copy()
array4[0] = 99
print(array4)
print(array3)

[99  2  3]
[1 2 3]


In [43]:
## view
array5 = array3.view()
array5[0] = 99
print(array5)
print(array3)

[99  2  3]
[99  2  3]


In [44]:
## array shapes
ar4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(ar4.shape)

(2, 5)


In [46]:
ar5 = np.array([1,2,3,4,5], ndmin=3) ## create an array with 3 dimension using ndmin using a vector with values 1,2,3,4,5 and verify that last dimension has value 5
print(ar5.shape)
print(ar5)

(1, 1, 5)
[[[1 2 3 4 5]]]


In [47]:
ar6 = np.array([-1,0,1])
newar = ar6.astype(bool)
print(newar)

[ True False  True]


In [49]:
## Reshaping into 3 X 2 Matrix
ar7 = np.array([1,2,3,4,5,6]).reshape(3,2)

In [50]:
print(ar7)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
## 2X3 Matrix
ar7 = np.array([1,2,3,4,5,6]).reshape(2,3)
print(ar7)

[[1 2 3]
 [4 5 6]]


In [52]:
## iterations 1-D
ar8 = np.array([1,2,3,4,5,6])
for i in ar8:
    print(i)

1
2
3
4
5
6


In [59]:
## 2D iteration
ar9 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in ar9:
    for j in i:
        print(i, j)

[1 2 3 4 5] 1
[1 2 3 4 5] 2
[1 2 3 4 5] 3
[1 2 3 4 5] 4
[1 2 3 4 5] 5
[ 6  7  8  9 10] 6
[ 6  7  8  9 10] 7
[ 6  7  8  9 10] 8
[ 6  7  8  9 10] 9
[ 6  7  8  9 10] 10


In [60]:
## 3D iterations
ar10 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

In [61]:
for i in ar10:
    for j in i:
        for k in j:
            print(i, j, k)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 3
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 4
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [1 2 3 4 5] 5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 6
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 7
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 8
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 9
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [ 6  7  8  9 10] 10
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 11
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 12
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 13
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 14
[[11 12 13 14 15]
 [16 17 18 19 20]] [11 12 13 14 15] 15
[[11 12 13 14 15]
 [16 17 18 19 20]] [16 17 18 19 20] 16
[[11 12 13 14 15]
 [16 17 18 19 20]] [16 17 18 19 20] 17
[[11 12 13 14 15]
 [16 17 18 19 20]] [16 17 18 19 20] 18
[[11 12 

In [62]:
for i in np.nditer(ar10):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [63]:
for i in np.nditer(ar10, flags=['buffered'], op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')
np.bytes_(b'13')
np.bytes_(b'14')
np.bytes_(b'15')
np.bytes_(b'16')
np.bytes_(b'17')
np.bytes_(b'18')
np.bytes_(b'19')
np.bytes_(b'20')


In [64]:
for i in np.nditer(ar10[:,::2]):
    print(i)

1
2
3
4
5
11
12
13
14
15


In [65]:
for idx, i in np.ndenumerate(ar10):
    print(idx, i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20


In [66]:
ar11 = np.array([[1,2,3], [4,5,6]]).reshape(6)
print(ar11)

[1 2 3 4 5 6]


In [68]:
ar11 = np.array([[1,2,3], [4,5,6]]).reshape(-1)
print(ar11)

[1 2 3 4 5 6]


In [70]:
## joins
ar12 = np.array([1,2])
ar13 = np.array([3,4])
print(np.concatenate((ar12, ar13)))

[1 2 3 4]


In [71]:
ar14 = np.array([[1,2,3], [4,5,6]])
ar15 = np.array([[7,8,9], [10,11,12]])
print(np.concatenate((ar14, ar15), axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [72]:
print(np.hstack((ar14, ar15)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [73]:
print(np.vstack((ar14, ar15)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [74]:
print(np.dstack((ar14, ar15)))

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
